FROM node:alpine

WORKDIR '/app/front'

COPY package.json .

RUN npm i

COPY . .

CMD ["npm","run","start"]

#docker build -t samb2/dockerworkspace -f Dockerfile.dev .
#docker run -p 3000:3000 -v $(pwd):/app/front samb2/dockerworkspace
