 version: '3'
 services:
   react-app:
     build:
       context: .
       dockerfile: Dockerfile.dev
     ports:
       - "3000:3000"
     volumes:
       - .:/app/front
   react-test:
     build:
       context: .
       dockerfile: Dockerfile.dev
     volumes:
       - .:/app/front
     command: ["npm","run","test"]
